# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I7xta8wdyINPRMtmnr-dZWISfVU54953
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
import joblib

df = pd.read_csv("Water Quality Testing.csv")

print(df.columns.tolist())

df.columns = df.columns.str.strip().str.lower()
print(df.columns.tolist())

df = df.rename(columns={
    "turbidity (ntu)": "turbidity",
    "conductivity (µs/cm)": "conductivity",
    "dissolved oxygen (mg/l)": "dissolved_oxygen",
    "temperature (°c)": "temperature"
})

print(df.columns.tolist())

df = df[(df["temperature"] >= 20) & (df["temperature"] <= 30)]

df["tds"] = 0.64 * df["conductivity"]

features = [
    "ph",
    "turbidity",
    "conductivity",
    "dissolved_oxygen",
    "tds"
]

df = df[features]
print(df.head())

df = df.fillna(df.median(numeric_only=True))

def who_label(row):
    if not (6.5 <= row["ph"] <= 8.5):
        return 0
    if row["turbidity"] >= 5:
        return 0
    if row["conductivity"] >= 400:
        return 0
    if not (6.5 <= row["dissolved_oxygen"] <= 8):
        return 0
    if row["tds"] >= 400:
        return 0
    return 1

df["safe"] = df.apply(who_label, axis=1)

print(df["safe"].value_counts())

X = df[features]
y = df["safe"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

gb_model = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train_scaled, y_train)

y_proba = gb_model.predict_proba(X_test_scaled)[:, 1]
y_pred = (y_proba >= 0.5).astype(int)

print(classification_report(y_test, y_pred))

def who_rule_check(sample):
    if sample["ph"] < 6.5 or sample["ph"] > 8.5:
        return 0
    if sample["turbidity"] >= 5:
        return 0
    if sample["conductivity"] >= 400:
        return 0
    if sample["dissolved_oxygen"] < 6.5 or sample["dissolved_oxygen"] > 8:
        return 0
    if sample["tds"] >= 400:
        return 0
    return None

def hybrid_predict(sample_df, threshold=0.5):

    sample_dict = sample_df.iloc[0].to_dict()

    # WHO hard check
    if who_rule_check(sample_dict) == 0:
        return {
            "Decision": 0,
            "Reason": "WHO rule violation",
            "ML_Probability": 0.0
        }

    sample_scaled = scaler.transform(sample_df)
    prob = gb_model.predict_proba(sample_scaled)[0][1]

    return {
        "Decision": int(prob >= threshold),
        "Reason": "ML confidence model",
        "ML_Probability": round(prob, 3)
    }

sample_safe = pd.DataFrame([[
    7.2, 2.0, 300, 7.2, 0.64 * 300
]], columns=features)

sample_unsafe = pd.DataFrame([[
    5.8, 7.5, 600, 5.0, 0.64 * 600
]], columns=features)

print(hybrid_predict(sample_safe))
print(hybrid_predict(sample_unsafe))

joblib.dump(gb_model, "gb_water_model.pkl")
joblib.dump(scaler, "scaler.pkl")

